baseURL: http://example.org/
languageCode: en-us
title: Lweiis's Blog
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

summaryLength: 10

menu:

  main:
    - name: Archive
      url: archives
      weight: 20
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 30
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 5

params:
  homeInfoParams:
    Title: 欢迎来到我的 Blog
    Content: "There is only one heroism in the world：to see the world as it is and to love it."

#  socialIcons: # optional
#    - name: "<platform>"
#        url: "<link>"
#    - name: "<platform 2>"
#        url: "<link2>"