baseURL: http://example.org/
languageCode: en-us
title: Lweiis's Blog
theme: github.com/adityatelange/hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

summaryLength: 10
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
  main:
    - identifier: posts
      name: Posts
      url: posts
      weight: 5
    - name: Search
      url: search
      weight: 10
    - name: Archive
      url: archives
      weight: 20
    - name: Categories
      url: categories
      weight: 30
    - name: Tags
      url: tags
      weight: 40
    - name: Series
      url: series
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: true # 分享按钮
#  ShowReadingTime: true # 显示帖子预估阅读时间
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  utteranc:
    enable: true
    repo: Lweiis/blog-utterances
    issueTerm: pathname
    theme: github-light
  comments: true
  homeInfoParams:
    Title: 欢迎来到我的 Blog
    Content: "There is only one heroism in the world：to see the world as it is and to love it."

#  socialIcons: # optional
#    - name: "<platform>"
#        url: "<link>"
#    - name: "<platform 2>"
#        url: "<link2>"